name: Redfin Scraper

on:
  schedule:
    - cron: "0 */12 * * *"   # runs every 12 hours
  workflow_dispatch:          # allows manual run from GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies (Chrome, Xvfb)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb unzip
          sudo apt-get install -y libxi6 libasound2
      
          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb


      - name: Install ChromeDriver that matches Chrome
        run: |
          CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //')
          CHROMEDRIVER_VERSION=$(curl https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION%%.*})
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run scraper with Xvfb
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99
          python redfin.py

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add redfin_data/*.csv
          git commit -m "Updated Redfin data" || echo "No changes"
          git push
